"""AI-assisted analysis via the Anthropic API, with a deterministic fallback.

If ANTHROPIC_API_KEY is set, section summaries and risk-change notes are
generated by Claude. Without a key the analyzer degrades gracefully to an
extractive summary so the pipeline (and CI) always works offline.
"""

from __future__ import annotations

import logging
import re

from ..config import Settings
from ..models import RedFlag, RiskChange, Section, SectionSummary

log = logging.getLogger(__name__)

_MAX_SECTION_CHARS = 60_000  # keep prompts bounded
_SUMMARY_SENTENCES = 4

_SUMMARY_PROMPT = """You are a financial analyst. Summarize the following section
"{title}" from a {form} SEC filing of {company} in 4-6 crisp bullet points.
Focus on facts, numbers and changes; no fluff, no investment advice.

<section>
{text}
</section>"""

_RISK_NOTE_PROMPT = """Compare the two versions of this risk factor from consecutive
{form} filings of {company}. In ONE sentence, state what materially changed
(scope, severity, new specifics). If the change is purely editorial, say so.

<previous>
{previous}
</previous>
<current>
{current}
</current>"""

_RED_FLAG_PROMPT = """You are a forensic accounting analyst. Given this evidence excerpt
from a {form} filing of {company}, assess in ONE sentence whether the flagged issue
"{label}" appears substantive or boilerplate, and why.

<evidence>
{evidence}
</evidence>"""


def extractive_summary(text: str, sentences: int = _SUMMARY_SENTENCES) -> str:
    """Deterministic fallback: first sentences + the longest 'substantive' sentence."""
    text = re.sub(r"\s+", " ", text).strip()
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9])", text)
    lead = parts[:sentences]
    summary = " ".join(lead)
    return summary[:1500] + ("…" if len(summary) > 1500 else "")


class AiAnalyzer:
    def __init__(self, settings: Settings, enabled: bool = True):
        self.settings = settings
        self._client = None
        if enabled and settings.ai_enabled:
            try:
                import anthropic

                self._client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
            except Exception as exc:  # pragma: no cover - import/env specific
                log.warning("Anthropic client unavailable (%s); using fallback.", exc)

    @property
    def enabled(self) -> bool:
        return self._client is not None

    def _complete(self, prompt: str, max_tokens: int = 700) -> str | None:
        if not self._client:
            return None
        try:
            msg = self._client.messages.create(
                model=self.settings.anthropic_model,
                max_tokens=max_tokens,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(b.text for b in msg.content if getattr(b, "type", "") == "text").strip()
        except Exception as exc:  # pragma: no cover - network specific
            log.warning("Anthropic call failed (%s); using fallback.", exc)
            return None

    # ---------------------------------------------------------------- public

    def summarize_section(self, section: Section, company: str, form: str) -> SectionSummary:
        text = section.text[:_MAX_SECTION_CHARS]
        answer = self._complete(
            _SUMMARY_PROMPT.format(title=section.title, form=form, company=company, text=text)
        )
        if answer:
            return SectionSummary(section.item, section.title, answer, method="ai")
        return SectionSummary(
            section.item,
            section.title,
            extractive_summary(text),
            method="extractive",
        )

    def annotate_risk_changes(
        self, changes: list[RiskChange], company: str, form: str, limit: int = 10
    ) -> None:
        """Add an AI note to the most relevant modified/new risks (in place)."""
        if not self.enabled:
            return
        interesting = [c for c in changes if c.status in ("modified", "new")][:limit]
        for change in interesting:
            note = self._complete(
                _RISK_NOTE_PROMPT.format(
                    form=form,
                    company=company,
                    previous=change.previous_excerpt or "(no prior version)",
                    current=change.current_excerpt,
                ),
                max_tokens=200,
            )
            if note:
                change.ai_note = note

    def review_red_flags(self, flags: list[RedFlag], company: str, form: str) -> None:
        """Append an AI assessment to each red flag's evidence (in place)."""
        if not self.enabled:
            return
        for flag in flags:
            note = self._complete(
                _RED_FLAG_PROMPT.format(
                    form=form, company=company, label=flag.label, evidence=flag.evidence
                ),
                max_tokens=200,
            )
            if note:
                flag.evidence = f"{flag.evidence}\n\nAI assessment: {note}"
