"""Render a FilingAnalysis to Markdown + JSON under reports/."""

from __future__ import annotations

import json
from pathlib import Path

from ..analysis.diff import summarize_changes
from ..models import FilingAnalysis

_SEVERITY_ICON = {"high": "🔴", "medium": "🟠", "low": "🟡"}


def _fmt_value(metric: str, value) -> str:
    if value is None:
        return "n/a"
    if metric == "eps_diluted":
        return f"{value:,.2f} USD"
    return f"{value:,.0f} USD"


def render_markdown(analysis: FilingAnalysis) -> str:
    ref = analysis.ref
    lines: list[str] = [
        f"# {ref.company.name} ({ref.company.ticker}) — {ref.form}",
        "",
        f"- **Filed:** {ref.filing_date}  ",
        f"- **Period:** {ref.report_date}  ",
        f"- **Accession:** `{ref.accession_number}`  ",
        f"- **Analysis mode:** {'AI (Anthropic)' if analysis.ai_used else 'deterministic heuristics (no API key)'}",
        "",
    ]

    if analysis.red_flags:
        lines += ["## 🚩 Red Flags", ""]
        for flag in sorted(analysis.red_flags, key=lambda f: f.severity != "high"):
            icon = _SEVERITY_ICON.get(flag.severity, "•")
            lines += [
                f"### {icon} {flag.label} (`{flag.flag_id}`, severity: {flag.severity})",
                "",
                f"> {flag.evidence}",
                "",
            ]
    else:
        lines += ["## 🚩 Red Flags", "", "No red flags detected by the rule set.", ""]

    if analysis.risk_changes:
        counts = summarize_changes(analysis.risk_changes)
        lines += [
            "## Risk Factor Changes (vs. prior filing)",
            "",
            f"**{counts['new']} new · {counts['modified']} modified · "
            f"{counts['unchanged']} unchanged · {counts['removed']} removed**",
            "",
        ]
        for status in ("new", "modified", "removed"):
            group = [c for c in analysis.risk_changes if c.status == status]
            if not group:
                continue
            lines += [f"### {status.capitalize()} ({len(group)})", ""]
            for c in group:
                excerpt = c.current_excerpt or c.previous_excerpt
                lines.append(f"- ({c.similarity:.2f}) {excerpt}")
                if c.ai_note:
                    lines.append(f"  - _AI note:_ {c.ai_note}")
            lines.append("")

    if analysis.financials.get("metrics"):
        lines += [
            "## Key Financials (XBRL)",
            "",
            f"Fiscal year: **{analysis.financials.get('fiscal_year')}**",
            "",
            "| Metric | Value | XBRL concept | Period end |",
            "|---|---:|---|---|",
        ]
        for metric, data in analysis.financials["metrics"].items():
            lines.append(
                f"| {metric.replace('_', ' ')} | {_fmt_value(metric, data.get('value'))} "
                f"| `{data.get('concept')}` | {data.get('end', '')} |"
            )
        lines.append("")

    if analysis.summaries:
        lines += ["## Section Summaries", ""]
        for s in analysis.summaries:
            lines += [f"### Item {s.item} — {s.title}", "", s.summary, ""]

    lines += [
        "---",
        "_Generated by [sec-filing-analyzer](https://github.com/OhneisB/SEC-Filing-Analyzer). "
        "Not investment advice._",
    ]
    return "\n".join(lines)


def write_reports(analysis: FilingAnalysis, reports_dir: Path) -> tuple[Path, Path]:
    ref = analysis.ref
    out_dir = reports_dir / ref.company.ticker / f"{ref.form}_{ref.report_date or ref.filing_date}"
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "report.md"
    json_path = out_dir / "report.json"
    md_path.write_text(render_markdown(analysis), encoding="utf-8")
    json_path.write_text(
        json.dumps(analysis.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return md_path, json_path
